### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-css-stealing-styles-xedvDK#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://KatieMFritz.github.io/MI-000-SS00-000-css-stealing-styles-xedvDK/) and meets the following criteria:

- [x] The page includes the name of your search engine in big letters (you can make it up), with a search `input` below it, then a button below that to run the search (the button doesn't have to do anything for this prototype)
- [x] The font size of the search engine name is at least 70 pixels, so that it's very easy to see
- [x] `span` elements are wrapped around each letter of the name, like this: `<span>G</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>`, so that they can be styled individually with classes
- [x] The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)
- [x] Inspect the `input` element at the bottom of the [_Prototyping states_ page of the lesson](https://msu.lansing.codes/courses/MI-000-SS00-000/lessons/css-stealing-styles/5) to create an identical-looking search box for your own site (it should even use the same styles on `hover` and `focus`)
- [x] The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)
- [x] There are no stylelint errors in your CSS (this will also be expected for all future projects)
- [x] All your CSS exists in a `.css` file

Make sure it's what you expected, and especially that the Stripe button is what you expected. I think I did it right, but it looks a little different on the white background.

**Comment by chrisvfritz** [comment]
Love the cat. Fix the button. 👍

**Comment by KatieMFritz** [comment]
@chrisvfritz okay, now?

**Comment by chrisvfritz** [comment]
Nice! :shipit:
